# Generated by Django 3.2.8 on 2021-10-15 16:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('resources', '0002_resourcepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CuratorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('resourcepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resourcepage')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resourcepage',),
        ),
        migrations.CreateModel(
            name='MusicResource',
            fields=[
                ('resourcepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resourcepage')),
                ('audio', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resourcepage',),
        ),
        migrations.CreateModel(
            name='PrayerResource',
            fields=[
                ('resourcepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resourcepage')),
                ('prayer', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resourcepage',),
        ),
        migrations.CreateModel(
            name='QuotationResource',
            fields=[
                ('resourcepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resourcepage')),
                ('quotation', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resourcepage',),
        ),
        migrations.RemoveField(
            model_name='resourcepage',
            name='body',
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='author',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='description',
            field=wagtail.core.fields.RichTextField(default='default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='source_link',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PoetryResource',
            fields=[
                ('resourcepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resourcepage')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resourcepage',),
        ),
    ]
