# Generated by Django 3.2.8 on 2021-10-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20211015_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcepage',
            name='intro',
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='date',
            field=models.DateField(verbose_name='Updated Date'),
        ),
    ]
