# Generated by Django 3.2.8 on 2021-10-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20211015_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poetryresource',
            old_name='body',
            new_name='poem',
        ),
    ]
