# Generated by Django 3.2.8 on 2021-10-15 16:40

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_rename_body_poetryresource_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatorpage',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='curatorpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='curatorpage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='poetryresource',
            name='poem',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
