# Generated by Django 3.2.8 on 2021-10-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20211015_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatorpage',
            name='name',
        ),
    ]
