# Generated by Django 3.2.8 on 2021-10-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_curatorpage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curatorpage',
            old_name='intro',
            new_name='about_me',
        ),
    ]
