# Generated by Django 3.2.8 on 2021-10-15 17:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20211015_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='curator',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.curatorpage'),
        ),
    ]
