# Generated by Django 3.2.8 on 2021-10-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_resourcetagindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicresource',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
    ]
