# Generated by Django 3.2.8 on 2021-10-15 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('resources', '0013_alter_musicresource_audio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicResource',
            new_name='AudioResource',
        ),
    ]
